<?php
/**
 * Member
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    piwam
 * @subpackage model
 * @author     Adrien Mogenet
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Member extends BaseMember
{
  /**
   * Get Member object as string
   *
   * @return string
   */
  public function __toString()
  {
    return $this->getFirstname() . ' ' . $this->getLastname();
  }

  /**
   * Overrides the setPassword to encrypt it
   *
   * @param   string  $v
   * @return  Member  $this
   */
  public function setPassword($v)
  {
    if ($v !== '')
    {
      return $this->_set('password', sha1($v));
    }
    else
    {
      return $this;
    }
  }

  /**
   * Overrides the setUsername method (manage the null case)
   *
   * @param   string  $v
   * @return  Member  $this
   */
  public function setUsername($v)
  {
    if ($v == "")
    {
      $v = null;
    }

    return $this->_set('username', $v);
  }

  /**
   * Returns the whole URI of user's picture, or 'no-picture' image
   * if he doesn't have one
   *
   * @return string
   */
  public function getPictureURI()
  {
    if ($this->getPicture())
    {
      return '/uploads/trombinoscope/' . $this->getPicture();
    }
    else
    {
      return 'no_picture';
    }
  }

  /**
   * Remove all existing credentials that have been set to the
   * Member previously
   */
  public function resetAcl()
  {
    $q = Doctrine_Query::create()
          ->delete('AclCredential c')
          ->where('c.member_id = ?', $this->getId());

    return $q->execute();
  }

  /**
   * Add a new credential to the member
   *
   * @param   string  $code   : Code of the AclAction
   */
  public function addCredential($code)
  {
    $credential = new AclCredential();
    $credential->setMemberId($this->getId());
    $credential->setAclAction(AclActionTable::getByCode($code));
    $credential->save();
  }

  /**
   * Check if the member has to pay a due or not
   *
   * @return  boolean
   */
  public function hasToPayDue()
  {
    $days = $this->getDaysBeforeNextDue();

    if (null === $days)
    {
      return false;
    }
    else
    {
      return $days <= 0;
    }
  }

  /**
   * Get the number of days that the member get to pay his due.
   * If result a negative, it means that user should have paid
   * the Due X days ago.
   *
   * If the member does not have to pay due (exempted) null is
   * returned
   *
   * @return  Mixed   Null if non available, relative integer otherwise
   */
  public function getDaysBeforeNextDue()
  {
    if ($this->getDueExempt() == true)
    {
      return null;
    }
    else
    {
      $lastDue = DueTable::getLastForMember($this->getId());
      $today = date('Y-m-d');

      if (null == $lastDue)
      {
        $nextDue = $this->getSubscriptionDate();
      }
      else
      {
        $dateCalculator = new DateTools($lastDue->getDate(), 'Y-m-d');
        $nextDue = $dateCalculator->add('mo', $lastDue->getDueType()->getPeriod());
      }

      return DateTools::getDaysBetween($today, $nextDue);
    }
  }

  /**
   * Overrides getter for City field.
   *
   * @return  string  well-formated city
   */
  public function getCity()
  {
    return mb_convert_case($this->_get('city'), MB_CASE_UPPER, "UTF8");
  }

  /**
   * Overrides getter for Lastname field
   *
   * @return  string  well-formated lastname
   */
  public function getLastname()
  {
    return mb_convert_case($this->_get('lastname'), MB_CASE_TITLE, "UTF8");
  }

  /**
   * Overrides getter for Firstname field
   *
   * @return  string  well-formated lastname
   */
  public function getFirstname()
  {
    return mb_convert_case($this->_get('firstname'), MB_CASE_TITLE, "UTF8");
  }

  /**
   * Overrides getter for Street field
   *
   * @return  string  well-formated lastname
   */
  public function getStreet()
  {
    return mb_convert_case($this->_get('street'), MB_CASE_TITLE, "UTF8");
  }

  /**
   * Get the whole adress of the member
   *
   * @return string
   */
  public function getCompleteAddress()
  {
    return StringTools::to7bit($this->getStreet()) . ', ' . $this->getZipcode() . ' ' . StringTools::to7bit($this->getCity());
  }

  /**
   * Returns information to display on Google Map
   */
  public function getInfoForGmap()
  {
    return '<b>' . $this->__toString() . '</b><br />' . $this->getCompleteAddress();
  }

  /**
   * Delete the Member object logically (it's not physically removed).
   * Erase username and passwords
   *
   * @return  Member
   */
  public function disable()
  {
    $this->setUsername(null);
    $this->setPassword(null);
    $this->setState(MemberTable::STATE_DISABLED);

    return $this;
  }

  /**
   * Get the number of Dues paid by the Member
   *
   * @return  integer
   */
  public function getNumberOfDues()
  {
    $dues = $this->getDue();

    return count($dues);
  }
}