<?php

/**
 * Status
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    piwam
 * @subpackage model
 * @author     Adrien Mogenet
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Status extends BaseStatus
{
  /**
   * Display Status object as String
   *
   * @return string
   */
  public function __toString()
  {
    return $this->getLabel();
  }

  /**
   * Get number of members who have the current status
   *
   * @return integer
   */
  public function countEnabledMembers()
  {
    return $this->getMembers()->count();
  }
}