<?php

/**
 * ksWCEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginKsWCEventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ksWCEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('KsWCEvent');
    }
}