<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/03/13 15:27:57

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'persistent' => true,
  'pooling' => true,
  'dsn' => 'mysql:dbname=Piwam;host=localhost',
  'username' => 'root',
  'password' => NULL,
  'encoding' => 'utf8',
  'name' => 'doctrine',
)),);
