<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/01/18 19:13:16
$this->security = array (
  'index' => 
  array (
    'credentials' => 'mailing',
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
