<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/03/20 19:49:18
sfConfig::add(array(
  'mod_kswdcalendar_enabled' => true,
  'mod_kswdcalendar_view_class' => 'sfPHP',
  'mod_kswdcalendar_is_internal' => false,
));
