<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/03/20 19:47:06
sfConfig::add(array(
  'mod_error_enabled' => true,
  'mod_error_view_class' => 'sfPHP',
  'mod_error_is_internal' => false,
));
