<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/01/18 19:09:04
sfConfig::add(array(
  'mod_quotation_enabled' => true,
  'mod_quotation_view_class' => 'sfPHP',
  'mod_quotation_is_internal' => false,
));
