<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/01/18 19:09:02
sfConfig::add(array(
  'mod_member_enabled' => true,
  'mod_member_view_class' => 'sfPHP',
  'mod_member_is_internal' => false,
));
