<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/03/21 18:41:49
$this->security = array (
  'newfirst' => 
  array (
    'is_secure' => false,
  ),
  'firstcreate' => 
  array (
    'is_secure' => false,
  ),
  'endregistration' => 
  array (
    'is_secure' => false,
  ),
  'search' => 
  array (
    'ccredentials' => 'list_member',
  ),
  'create' => 
  array (
    'credentials' => 'add_member',
  ),
  'new' => 
  array (
    'credentials' => 'add_member',
  ),
  'delete' => 
  array (
    'credentials' => 'del_member',
  ),
  'requestsubscription' => 
  array (
    'is_secure' => false,
  ),
  'createpending' => 
  array (
    'is_secure' => false,
  ),
  'pending' => 
  array (
    'is_secure' => false,
  ),
  'validate' => 
  array (
    'credentials' => 'edit_member',
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
