<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/03/20 22:04:18
sfConfig::add(array(
  'mod_login_enabled' => true,
  'mod_login_view_class' => 'sfPHP',
  'mod_login_is_internal' => false,
));
