<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/01/18 19:13:16
sfConfig::add(array(
  'mod_mailing_enabled' => true,
  'mod_mailing_view_class' => 'sfPHP',
  'mod_mailing_is_internal' => false,
));
