<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/01/18 19:09:02
sfConfig::add(array(
  'mod_login_enabled' => true,
  'mod_login_view_class' => 'sfPHP',
  'mod_login_is_internal' => false,
));
