<?php

/**
 * DebtTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DebtTable extends PluginDebtTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DebtTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Debt');
    }
}