<?php

/**
 * Debt
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    piwam
 * @subpackage model
 * @author     Adrien Mogenet
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Debt extends PluginDebt
{
}
