<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AclCredential', 'doctrine');

/**
 * BaseAclCredential
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $member_id
 * @property integer $acl_action_id
 * @property AclAction $AclAction
 * @property Member $Member
 * 
 * @method integer       getId()            Returns the current record's "id" value
 * @method integer       getMemberId()      Returns the current record's "member_id" value
 * @method integer       getAclActionId()   Returns the current record's "acl_action_id" value
 * @method AclAction     getAclAction()     Returns the current record's "AclAction" value
 * @method Member        getMember()        Returns the current record's "Member" value
 * @method AclCredential setId()            Sets the current record's "id" value
 * @method AclCredential setMemberId()      Sets the current record's "member_id" value
 * @method AclCredential setAclActionId()   Sets the current record's "acl_action_id" value
 * @method AclCredential setAclAction()     Sets the current record's "AclAction" value
 * @method AclCredential setMember()        Sets the current record's "Member" value
 * 
 * @package    piwam
 * @subpackage model
 * @author     Adrien Mogenet
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseAclCredential extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('piwam_acl_credential');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('member_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('acl_action_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AclAction', array(
             'local' => 'acl_action_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}