<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ConfigCategory', 'doctrine');

/**
 * BaseConfigCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property string $label
 * @property Doctrine_Collection $ConfigVariable
 * 
 * @method string              getCode()           Returns the current record's "code" value
 * @method string              getLabel()          Returns the current record's "label" value
 * @method Doctrine_Collection getConfigVariable() Returns the current record's "ConfigVariable" collection
 * @method ConfigCategory      setCode()           Sets the current record's "code" value
 * @method ConfigCategory      setLabel()          Sets the current record's "label" value
 * @method ConfigCategory      setConfigVariable() Sets the current record's "ConfigVariable" collection
 * 
 * @package    piwam
 * @subpackage model
 * @author     Adrien Mogenet
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseConfigCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('piwam_config_category');
        $this->hasColumn('code', 'string', 25, array(
             'type' => 'string',
             'primary' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('label', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ConfigVariable', array(
             'local' => 'code',
             'foreign' => 'category_code'));
    }
}