<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Data', 'doctrine');

/**
 * BaseData
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $config_key
 * @property string $value
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method string  getConfigKey()  Returns the current record's "config_key" value
 * @method string  getValue()      Returns the current record's "value" value
 * @method Data    setId()         Sets the current record's "id" value
 * @method Data    setConfigKey()  Sets the current record's "config_key" value
 * @method Data    setValue()      Sets the current record's "value" value
 * 
 * @package    piwam
 * @subpackage model
 * @author     Adrien Mogenet
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseData extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('piwam_data');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('config_key', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('value', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}