<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AclModule', 'doctrine');

/**
 * BaseAclModule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $label
 * @property Doctrine_Collection $AclAction
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getLabel()     Returns the current record's "label" value
 * @method Doctrine_Collection getAclAction() Returns the current record's "AclAction" collection
 * @method AclModule           setId()        Sets the current record's "id" value
 * @method AclModule           setLabel()     Sets the current record's "label" value
 * @method AclModule           setAclAction() Sets the current record's "AclAction" collection
 * 
 * @package    piwam
 * @subpackage model
 * @author     Adrien Mogenet
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseAclModule extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('piwam_acl_module');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('label', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AclAction', array(
             'local' => 'id',
             'foreign' => 'acl_module_id'));
    }
}