<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Income', 'doctrine');

/**
 * BaseIncome
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $label
 * @property integer $association_id
 * @property decimal $amount
 * @property integer $account_id
 * @property integer $activity_id
 * @property date $date
 * @property boolean $received
 * @property integer $created_by
 * @property integer $updated_by
 * @property Association $Association
 * @property Account $Account
 * @property Activity $Activity
 * @property Member $CreatedByMember
 * @property Member $UpdatedByMember
 * @property Doctrine_Collection $Debt
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getLabel()           Returns the current record's "label" value
 * @method integer             getAssociationId()   Returns the current record's "association_id" value
 * @method decimal             getAmount()          Returns the current record's "amount" value
 * @method integer             getAccountId()       Returns the current record's "account_id" value
 * @method integer             getActivityId()      Returns the current record's "activity_id" value
 * @method date                getDate()            Returns the current record's "date" value
 * @method boolean             getReceived()        Returns the current record's "received" value
 * @method integer             getCreatedBy()       Returns the current record's "created_by" value
 * @method integer             getUpdatedBy()       Returns the current record's "updated_by" value
 * @method Association         getAssociation()     Returns the current record's "Association" value
 * @method Account             getAccount()         Returns the current record's "Account" value
 * @method Activity            getActivity()        Returns the current record's "Activity" value
 * @method Member              getCreatedByMember() Returns the current record's "CreatedByMember" value
 * @method Member              getUpdatedByMember() Returns the current record's "UpdatedByMember" value
 * @method Doctrine_Collection getDebt()            Returns the current record's "Debt" collection
 * @method Income              setId()              Sets the current record's "id" value
 * @method Income              setLabel()           Sets the current record's "label" value
 * @method Income              setAssociationId()   Sets the current record's "association_id" value
 * @method Income              setAmount()          Sets the current record's "amount" value
 * @method Income              setAccountId()       Sets the current record's "account_id" value
 * @method Income              setActivityId()      Sets the current record's "activity_id" value
 * @method Income              setDate()            Sets the current record's "date" value
 * @method Income              setReceived()        Sets the current record's "received" value
 * @method Income              setCreatedBy()       Sets the current record's "created_by" value
 * @method Income              setUpdatedBy()       Sets the current record's "updated_by" value
 * @method Income              setAssociation()     Sets the current record's "Association" value
 * @method Income              setAccount()         Sets the current record's "Account" value
 * @method Income              setActivity()        Sets the current record's "Activity" value
 * @method Income              setCreatedByMember() Sets the current record's "CreatedByMember" value
 * @method Income              setUpdatedByMember() Sets the current record's "UpdatedByMember" value
 * @method Income              setDebt()            Sets the current record's "Debt" collection
 * 
 * @package    piwam
 * @subpackage model
 * @author     Adrien Mogenet
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseIncome extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('piwam_income');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('label', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('association_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('amount', 'decimal', 10, array(
             'type' => 'decimal',
             'notnull' => true,
             'length' => '10',
             'scale' => ' 2',
             ));
        $this->hasColumn('account_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('activity_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('date', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => '25',
             ));
        $this->hasColumn('received', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('updated_by', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Association', array(
             'local' => 'association_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Account', array(
             'local' => 'account_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Activity', array(
             'local' => 'activity_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Member as CreatedByMember', array(
             'local' => 'created_by',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Member as UpdatedByMember', array(
             'local' => 'updated_by',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('Debt', array(
             'local' => 'id',
             'foreign' => 'income_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}