<?php

/**
 * BaseKsWCEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $subject
 * @property string $description
 * @property timestamp $start_time
 * @property timestamp $end_time
 * @property boolean $is_all_day_event
 * @property varchar $color
 * @property varchar $recurring_rule
 * @property string $listUser
 * 
 * @method varchar   getSubject()          Returns the current record's "subject" value
 * @method string    getDescription()      Returns the current record's "description" value
 * @method timestamp getStartTime()        Returns the current record's "start_time" value
 * @method timestamp getEndTime()          Returns the current record's "end_time" value
 * @method boolean   getIsAllDayEvent()    Returns the current record's "is_all_day_event" value
 * @method varchar   getColor()            Returns the current record's "color" value
 * @method varchar   getRecurringRule()    Returns the current record's "recurring_rule" value
 * @method string    getListUser()         Returns the current record's "listUser" value
 * @method KsWCEvent setSubject()          Sets the current record's "subject" value
 * @method KsWCEvent setDescription()      Sets the current record's "description" value
 * @method KsWCEvent setStartTime()        Sets the current record's "start_time" value
 * @method KsWCEvent setEndTime()          Sets the current record's "end_time" value
 * @method KsWCEvent setIsAllDayEvent()    Sets the current record's "is_all_day_event" value
 * @method KsWCEvent setColor()            Sets the current record's "color" value
 * @method KsWCEvent setRecurringRule()    Sets the current record's "recurring_rule" value
 * @method KsWCEvent setListUser()         Sets the current record's "listUser" value
 * 
 * @package    piwam
 * @subpackage model
 * @author     Adrien Mogenet
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKsWCEvent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ks_w_c_event');
        $this->hasColumn('subject', 'varchar', 64, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 64,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 4000,
             ));
        $this->hasColumn('start_time', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('end_time', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('is_all_day_event', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('color', 'varchar', 10, array(
             'type' => 'varchar',
             'length' => 10,
             ));
        $this->hasColumn('recurring_rule', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('listUser', 'string', 8000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 8000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}