<?php

/**
 * MemberExtraValue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    piwam
 * @subpackage model
 * @author     Adrien Mogenet
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class MemberExtraValue extends BaseMemberExtraValue
{
  /**
   * Store any type of value in database (serialized field)
   *
   * @param   Mixed             $value
   * @return  MemberExtraValue
   */
  public function setValue($value)
  {
    $this->_set('value', serialize($value));

    return $this;
  }

  /**
   * Retrieved variable stored in 'value' field
   *
   * @return Mixed
   */
  public function getValue()
  {
    return unserialize($this->_get('value'));
  }

  /**
   * Get a ready-to-display string of 'value' field. If it's an array,
   * this is (currently) obviously a date, so we merge the values
   * into a -formatted- string
   *
   * @return  string
   */
  public function getFormattedValue()
  {
    $params = $this->getValue();

    if (is_array($params))
    {
      foreach ($params as $key => $value)
      {
        if (strlen($params[$key]) < 2)
        {
          $params[$key] = '0' . $params[$key];
        }
      }

      return implode('/', $params);
    }

    return $params;
  }
}
