
# If we want to register the first member of
# an association, we authorize the access but
# anyway we check if the session variable
# `association_id` which is stored temporary
# has been set correctly

newfirst:
  is_secure:    false
  
firstcreate:
  is_secure:    false
  
endregistration:
  is_secure:    false
  
index:
  # Credentials are checked in action class since revision r154
  #credentials:  list_member
  
search:
  ccredentials: list_member

create:
  credentials:  add_member

new:
  credentials:  add_member

delete:
  credentials:  del_member

requestsubscription:
  is_secure:    false
  
createpending:
  is_secure:    false
  
pending:
  is_secure:    false
  
validate :
  credentials:  edit_member
  
edit:

  # To strictly forbid users to edit their own profile, and just allow
  # users who have the credential, just uncomment the following line
  #credentials:  edit_member
  
  
show:

  # To strictly forbid users to show their own profile, and just allow
  # users who have the credential, just uncomment the following line
  #credentials:  show_member
  
