<?php
/**
 * Debt
 * 
 * This class has been auto-generated by the Doctrine ORM Framework. But it
 * was empty and filled by the developer ;-)
 *
 * This class represents an entry of the Debt table. By default, it has
 * default accessors generated by the framework :
 *
 *  - get/setMemberId($value)
 *  - get/setIncomeId($value)
 *
 * But if we need to add extra computations, accessors or behaviours, we
 * have to declare and implements our custom method into this class.
 *
 *
 * To sum up :
 * -----------
 * The DebtTable class is used to retrieve Debt rows (as objects !)
 * This Debt class represent each of these Debt records.
 *
 * 
 * @package    piwam
 * @subpackage model
 * @author     Adrien Mogenet
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Debt extends PluginDebt
{
  /**
   * Here is an example of extra method we could add.
   * It gets the statement of the debt (if it has been paid or not).
   *
   * Into the introduction comments I said that the framework generated
   * default accessors for each field, actually it also allows to retrieve
   * these fields as objects since we declare the relation into the file
   * schema.yml properly.
   *
   *    getMemberId() returns an integer => getMember() returns the Member
   *    getIncomeId() returns an integer => getIncome() returns the Income
   *
   * So we are using the Income object to call its "getReceived" method, which
   * indicates if the Income has been received by the association or not.
   * Note that code has been well commented by framework and developers, so
   * your IDE should autocomplete these calls correctly !
   *
   * @return  boolean
   */
  public function hasBeenPaid()
  {
    return $this->getIncome()->getReceived();
  }

  /**
   * As an exercice, you can try to compute the amount of the member has to
   * pay according to the creation date and the amount of this Dept.
   */
  public function getRealAmount()
  {
    // may be useful :
    // documentation of Income class ;-)
  }
}
